### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by hamood192244** [Mobius1/XpM#1]
hello 
First i want to thank you for this great reassure <3

i want a small help here from you please 
how to lets the player to get "xp" from there job when they deliver the final items
i use the "esx_jobs"
i try all possible things what i have and i don't get any result. can you help me please 

thank you <3

**Comment by hamood192244** [comment]
- [ ]

**Comment by hamood192244** [comment]
Can you help ?>

**Comment by Mobius1** [comment]
Depending on the job, you'd need to look in the server script, usually `server/main.lua`, find the event handler that's triggered when the player completes the job and add `TriggerClientEvent('XpM:Add', source, xp)` to it.

**Comment by hamood192244** [comment]
Thank you for your answer 

TriggerClientEvent ('XpM: Add', **source**, **xp**)

I understand what is the value of **xp**
But what is the meaning of the **source**
What is the number i enter

**Comment by hamood192244** [comment]
Citizen.CreateThread(function()
	while true do
		Citizen.Wait(1000)
		local timeNow = os.clock()

		for playerId,data in pairs(playersWorking) do
			Citizen.Wait(10)
			local xPlayer = ESX.GetPlayerFromId(playerId)

			-- is player still online?
			if xPlayer then
				local distance = #(xPlayer.getCoords(true) - data.zoneCoords)

				-- player still within zone limits?
				if distance <= data.zoneMaxDistance then
					-- calculate the elapsed time
					local timeElapsed = timeNow - data.time

					if timeElapsed > data.jobItem[1].time then
						data.time = os.clock()

						for k,v in ipairs(data.jobItem) do
							local itemQtty, requiredItemQtty = 0, 0

							if v.name ~= _U('delivery') then
								itemQtty = xPlayer.getInventoryItem(v.db_name).count
							end

							if data.jobItem[1].requires ~= 'nothing' then
								requiredItemQtty = xPlayer.getInventoryItem(data.jobItem[1].requires).count
							end
			
							if v.name ~= _U('delivery') and itemQtty >= v.max then
								xPlayer.showNotification(_U('max_limit', v.name))
								playersWorking[playerId] = nil
							elseif v.requires ~= 'nothing' and requiredItemQtty <= 0 then
								xPlayer.showNotification(_U('not_enough', data.jobItem[1].requires_name))
								playersWorking[playerId] = nil
							else
								if v.name ~= _U('delivery') then
									-- chances to drop the item
									if v.drop == 100 then
										xPlayer.addInventoryItem(v.db_name, v.add)
									else
										local chanceToDrop = math.random(100)
										if chanceToDrop <= v.drop then
											xPlayer.addInventoryItem(v.db_name, v.add)
										end
									end
								else
									xPlayer.addMoney(v.price)
								end
							end
						end
			
						if data.jobItem[1].requires ~= 'nothing' then
							local itemToRemoveQtty = xPlayer.getInventoryItem(data.jobItem[1].requires).count
							if itemToRemoveQtty > 0 then
								xPlayer.removeInventoryItem(data.jobItem[1].requires, data.jobItem[1].remove)
							end
						end
					end
				else
					playersWorking[playerId] = nil
				end
			else
				playersWorking[playerId] = nil
			end
		end
	end
end)

**Comment by hamood192244** [comment]
if v.name ~= _U('delivery') then
								itemQtty = xPlayer.getInventoryItem(v.db_name).count
							end

							if data.jobItem[1].requires ~= 'nothing' then
								requiredItemQtty = xPlayer.getInventoryItem(data.jobItem[1].requires).count
							end
			
							if v.name ~= _U('delivery') and itemQtty >= v.max then
								xPlayer.showNotification(_U('max_limit', v.name))
								playersWorking[playerId] = nil
							elseif v.requires ~= 'nothing' and requiredItemQtty <= 0 then
								xPlayer.showNotification(_U('not_enough', data.jobItem[1].requires_name))
								playersWorking[playerId] = nil
							else
								if v.name ~= _U('delivery') then
									-- chances to drop the item
									if v.drop == 100 then
										xPlayer.addInventoryItem(v.db_name, v.add)
									else
										local chanceToDrop = math.random(100)
										if chanceToDrop <= v.drop then
											xPlayer.addInventoryItem(v.db_name, v.add)
										end
									end
								else
									xPlayer.addMoney(v.price)
								end
							end
						end

**Comment by hamood192244** [comment]
where can i put
TriggerClientEvent('XpM:Add', source, xp)

please :( small help

**Comment by Mobius1** [comment]
`xPlayer.addMoney(v.price)` is where the player gets paid so add it after that line and use `playerId`:

```lua
xPlayer.addMoney(v.price)

TriggerClientEvent('XpM:Add', playerId, xp) -- add this
```

**Comment by hamood192244** [comment]
doesn't work </3 
and i try with esx_xp 
it's same

**Comment by hamood192244** [comment]
https://gyazo.com/f5a4d5fe5a1b6c20d016582de1a7fb78
